services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $extension: '@Zikula\FormiculaModule\ZikulaFormiculaModule'
            $cacheDir: '%kernel.cache_dir%'

    Zikula\FormiculaModule\:
        resource: '../../*'
        exclude: '../../{bootstrap.php,Tests,vendor}'

    Zikula\FormiculaModule\Helper\:
        resource: '../../Helper/*'
        lazy: true
