services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $extension: '@Zikula\FormiculaModule\ZikulaFormiculaModule'
            $projectDir: '%kernel.project_dir%'
            $cacheDir: '%kernel.project_dir%/public/formicula/cache'

    Zikula\FormiculaModule\:
        resource: '../../*'
        exclude: '../../{bootstrap.php,Tests,vendor}'

    Zikula\FormiculaModule\Helper\:
        resource: '../../Helper/*'
        lazy: true

    _instanceof:
        Zikula\ExtensionsModule\ModuleInterface\Content\ContentTypeInterface:
            bind:
                $twigLoader: '@twig.loader'
                $permissionHelper: '@?Zikula\ContentModule\Helper\PermissionHelper'
