services:
    zikula_formicula_module.container.link_container:
        class: Zikula\FormiculaModule\Container\LinkContainer
        arguments:
         - '@translator.default'
         - '@jms_i18n_routing.router'
         - '@zikula_permissions_module.api.permission'
        tags: ['zikula.link_container']

    twig.extension.zikula_formicula_module:
        class: Zikula\FormiculaModule\Twig\TwigExtension
        public: false
        arguments:
            - '@zikula_formicula_module.helper.captcha_helper'
        tags: ['twig.extension']

    zikula_formicula_module.listener.third_party_listener:
        class: Zikula\FormiculaModule\Listener\ThirdPartyListener
        tags: ['kernel.event_subscriber']

    zikula_formicula_module.helper.captcha_helper:
        class: Zikula\FormiculaModule\Helper\CaptchaHelper
        lazy: true
        arguments:
            - '@translator.default'
            - '@zikula_extensions_module.api.variable'
            - '@zikula_permissions_module.api.permission'
            - '@zikula_formicula_module.helper.environment_helper'
            - '@jms_i18n_routing.router'
            - '@request_stack'

    zikula_formicula_module.helper.environment_helper:
        class: Zikula\FormiculaModule\Helper\EnvironmentHelper
        lazy: true
        arguments:
            - '@kernel'
            - '@translator.default'
            - '@zikula_extensions_module.api.variable'
            - '@request_stack'

    zikula_formicula_module.hook_subscriber.ui_hooks.forms:
        class: Zikula\FormiculaModule\HookSubscriber\FormUiHooksSubscriber
        arguments:
            - '@translator.default'
        tags:
            - { name: zikula.hook_subscriber, areaName: 'subscriber.zikulaformiculamodule.ui_hooks.forms' }

    Zikula\FormiculaModule\ContentType\FormType:
        parent: zikula.content_type.base
        shared: false
        calls:
            - [setRequestStack, ['@request_stack']]
            - [setHttpKernel, ['@http_kernel']]
        tags: ['zikula.content_type']
    Zikula\FormiculaModule\ContentType\Form\Type\FormType:
        parent: zikula.content_type.form.base
        arguments:
            - '@doctrine.orm.entity_manager'
        tags: ['form.type']
